# Generated by Django 5.1.2 on 2024-10-28 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_review_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='level',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product_management.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_management.categories'),
        ),
    ]
