# Generated by Django 5.1.2 on 2024-11-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
